---
title: "Teaching and Mentoring"
format: html
---
## Courses Taught

Intermediate Analysis II (MAT 127B, Summer 2025, UC Davis)

Vector Analysis (MAT 21D, Summer 2024, UC Davis)

Vector Analysis (MAT 21D, Summer 2023, UC Davis)

Calculus: Partial Derivatives and Series (MAT 21C, Summer 2022, UC Davis)

Modern Physics Labratory (PHYS 20CL, Summer 2021, UCSB)

Modern Physics Labratory (PHYS 20CL, Summer 2020, UCSB)

## Teaching Assistant
Precalculus, Calculus I-IV, Calculus for Biology and Medicine II-III,  Introduction to Abstract Mathematics, Graduate Analysis II.

## Mentorship
I have served as a mentor for 8 undergraduate reading projects on the following topics: [C* Algebras](images/Abhi%20Poster.pdf){target="_blank"}, [Special Relativity](images/Claudio%20Poster.pdf){target="_blank"}, [The Fourier Transform in Circuit Analysis](images/Selene%20Poster.pdf){target="_blank"}, [The Cosmological Constant](images/Hannah%20Poster.pdf){target="_blank"}, [Measure theory and the Dirac Delta function](images/Nic%20Slides.pdf){target="_blank"}, [Differential Geometry](images/Yaotian%20Slides.pdf){target="_blank"}, Quantum Computing, and Knot Theory.

